### PR TITLE
refactoring of kin

### PR DESCRIPTION
**Pull request by jaredo**
@rudyarthur see what you think. 

Key points:
- added multiple kinship estimators with `-M` as discussed in #6 
- frequencies provided via `-F` and `-T/-R` now only for subsetting by site (generally I would like to keep things as consistent with bcftools as possible)
- default behaviour is now to estimate allele frequencies from data but will print warning if N<50
- I stopped storing the IBS values in memory and calculate them on the fly. The downside here is that the ordering of the output pairs is random, but I don't think this is matters (`relatives` still works fine)
- I am trying to consolidate all the kinship calculations into a `Kinship` class. We want to use your bitset code for internal work so this is a useful separation.

I know for current sample sizes we can fit the matrix in memory easily, but I want to extend this work to something that scales to crazy sizes using [LSH](https://en.wikipedia.org/wiki/Locality-sensitive_hashing).

The speed differences between this version and the first release seem negligble: https://gist.github.com/jaredo/807bb9f66d1dd62e2e9832d0c4beb22c

```
$ ./akt kin

About: Calculate kinship/IBD statistics from a multisample BCF/VCF
Usage: akt kin [options] <in.bcf>
Expects input.bcf to contain genotypes.

Kinship calculation options:
         -k --minkin:                   threshold for relatedness output (none)
         -F --freq-file:                a file containing population allele frequencies to use in kinship calculation
         -M --method:                   type of estimator. 0:plink (default) 1:king-robust 2:genetic-relationship-matrix
         -a --aftag:                    allele frequency tag (default AF)
         -n --nthreads:                 num threads

Site filtering options:
         -R --regions-file:             restrict to regions listed in a file
         -r --regions:                  chromosome region
         -T --targets-file:             similar to -R but streams rather than index-jumps
         -t --targets:                  similar to -r but streams rather than index-jumps
         -m --maf:                      minimum MAF
         -h --thin:                     keep every h variants

Sample filtering options:
         -s --samples:                  list of samples
         -S --samples-file:             list of samples, file
```

### CODE REVIEW

**Comment by rudyarthur** [comment]
Why is there no message for -f? And does -f still work? I am of two minds, I kind of like this option, but -S  is probably sufficient and I like removing options as a general rule.
- frequencies provided via -F

Fine, as long as the documentation, tests and examples are updated. And I think this makes the usage inconsistent with the pca and IBD segment, code where -R is still used.
- default behaviour is now to estimate allele frequencies from data but will print warning if N<50

I don't like this. I kind of want to force people to use a site list, since the temptation will be to type

```
akt kin input.vcf
```

For some huge 20G 1000 sample whole genome VCF. When using so many sites is a huge waste of time. It should at least strongly complain at the user if either -F or -R aren't used.

**Comment by jaredo** [comment]
-  Would a warning when neither `-R` or `-F` are provided suffice or should we just refuse to run in that case?

I suppose someone might want to do it, so it should run. I will leave you to decide the requisite level of alarm, but I think you should write something like 'akt kin does not require a dense marker set, consider subsetting with -R data/panel.vcf'

Happy for you to merge anyway.

**Comment by jaredo** [comment]
..actually I should also update the relevent docs before this merge

**Comment by jaredo** [comment]
How about:

```
 -f --force:            run kin without -R/-T/-F
```

**Comment by rudyarthur** [comment]
Sure

**Comment by jaredo** [comment]
closing and pulling updated branch

**Pull request closed without merging**
